--- pyproject.toml.orig	2023-09-28 16:44:16 UTC
+++ pyproject.toml
@@ -40,7 +40,7 @@ classifiers = [
     "Topic :: Utilities",
 ]
 dependencies = [
-    "awkward_cpp==24",
+    "awkward_cpp==25",
     "importlib_metadata>=4.13.0;python_version < \"3.12\"",
     "numpy>=1.18.0",
     "packaging",
