--- pyproject.toml.orig	2022-06-28 16:50:47 UTC
+++ pyproject.toml
@@ -31,7 +31,7 @@ all = [
     "mccabe>=0.6.0,<0.7.0",
     "pycodestyle>=2.8.0,<2.9.0",
     "pydocstyle>=2.0.0",
-    "pyflakes>=2.4.0,<2.5.0",
+    "pyflakes>=2.4.0",
     "pylint>=2.5.0",
     "rope>=0.10.5",
     "yapf",
@@ -42,7 +42,7 @@ pydocstyle = ["pydocstyle>=2.0.0"]
 mccabe = ["mccabe>=0.6.0,<0.7.0"]
 pycodestyle = ["pycodestyle>=2.8.0,<2.9.0"]
 pydocstyle = ["pydocstyle>=2.0.0"]
-pyflakes = ["pyflakes>=2.4.0,<2.5.0"]
+pyflakes = ["pyflakes>=2.4.0"]
 pylint = ["pylint>=2.5.0"]
 rope = ["rope>0.10.5"]
 yapf = ["yapf", "whatthepatch>=1.0.2,<2.0.0"]
