--- src/ptserver/pts.c.orig	2021-01-14 21:08:41 UTC
+++ src/ptserver/pts.c
@@ -366,98 +366,6 @@ CreateUser(struct cmd_syndesc *as, void *arock)
 }
 
 
-#ifdef notdef
-static int
-GetNameOrId(struct cmd_syndesc *as, struct idlist *lids, struct namelist *lnames)
-{
-    afs_int32 code = 0;
-    int n = 0;
-    struct cmd_item *i;
-    int goodCount;
-
-    if (!(as->parms[0].items || as->parms[1].items)) {
-	afs_com_err(whoami, 0, "must specify either a name or an id.");
-	return -1;
-    }
-    if (as->parms[0].items && as->parms[1].items) {
-	afs_com_err(whoami, 0, "can't specify both a name and id.");
-	return -1;
-    }
-
-    goodCount = 0;
-    lids->idlist_len = 0;
-    lids->idlist_val = 0;
-
-    if (as->parms[0].items) {	/* name */
-	struct namelist names;	/* local copy, if not ret. names */
-	struct namelist *nl;
-
-	names.namelist_val = 0;	/* so it gets freed later if needed */
-	if (lnames)
-	    nl = lnames;
-	else
-	    nl = &names;
-
-	n = 0;			/* count names */
-	for (i = as->parms[0].items; i; i = i->next)
-	    n++;
-	nl->namelist_val = malloc(n * PR_MAXNAMELEN);
-	nl->namelist_len = n;
-	n = 0;
-	for (i = as->parms[0].items; i; i = i->next)
-	    strncpy(nl->namelist_val[n++], i->data, PR_MAXNAMELEN);
-
-	code = pr_NameToId(nl, lids);
-	if (code)
-	    afs_com_err(whoami, code, "so couldn't look up names");
-	else {
-	    for (n = 0; n < lids->idlist_len; n++) {
-		if ((lids->idlist_val[n] == ANONYMOUSID)) {
-		    afs_com_err(whoami, PRNOENT, "so couldn't look up id for %s",
-			    nl->namelist_val[n]);
-		} else
-		    goodCount++;
-	    }
-	    /* treat things as working if any of the lookups worked */
-	    if (goodCount == 0)
-		code = PRNOENT;
-	}
-
-	if (names.namelist_val)
-	    free(names.namelist_val);
-    } else if (as->parms[1].items) {	/* id */
-	n = 0;
-	for (i = as->parms[1].items; i; i = i->next)
-	    n++;
-	lids->idlist_val = malloc(n * sizeof(afs_int32));
-	lids->idlist_len = n;
-	n = 0;
-	for (i = as->parms[1].items; i; i = i->next) {
-	    code = util_GetInt32(i->data, &lids->idlist_val[n]);
-	    if (code)
-		afs_com_err(whoami, code =
-			PRNOENT, "because a bogus id '%s' was specified",
-			i->data);
-	    n++;
-	}
-	if (!code && lnames) {
-	    lnames->namelist_val = 0;
-	    lnames->namelist_len = 0;
-	    code = pr_IdToName(lids, lnames);
-	    if (code)
-		afs_com_err(whoami, code, "translating ids");
-	}
-    }
-    if (code) {
-	if (lids->idlist_val)
-	    free(lids->idlist_val);
-	return -1;
-    }
-    return 0;
-}
-#endif
-
-
 static int
 GetNameOrId(struct cmd_syndesc *as, struct idlist *lids,
 	    struct namelist *lnames)
