--- src/libadmin/vos/vsprocs.c.orig	2021-01-14 21:08:41 UTC
+++ src/libadmin/vos/vsprocs.c
@@ -1181,109 +1181,6 @@ DelVol(struct rx_connection *conn, afs_uint32 vid, afs
 #define ONERROR(ec, ep, es) if (ec) { fprintf(STDERR, (es), (ep)); error = (ec); goto rfail; }
 #define ERROREXIT(ec) { error = (ec); goto rfail; }
 
-#if 0				/* doesn't appear to be used, why compile it */
-static int
-CloneVol(afs_cell_handle_p cellHandle, struct rx_connection *conn,
-	 afs_uint32 rwvid, afs_int32 part, afs_uint32 * rovidp, int nottemp,
-	 struct nvldbentry *entry, afs_int32 * vidCreateDate, afs_status_p st)
-{
-    int rc = 0;
-    afs_status_t tst = 0, etst = 0;
-    afs_int32 rcode = 0, tid = 0;
-    struct volser_status volstatus;
-    char vname[64];
-
-    /* Begin transaction on RW volume marking it busy (clients will wait) */
-    tst = AFSVolTransCreate(conn, rwvid, part, ITBusy, &tid);
-    if (tst) {
-	goto fail_CloneVol;
-    }
-
-    /* Get the RO volume id. Allocate a new one if need to */
-    *rovidp = entry->volumeId[ROVOL];
-    if (*rovidp == INVALID_BID) {
-	tst = ubik_VL_GetNewVolumeId(cellHandle->vos, 0, 1, rovidp);
-	if (tst) {
-	    goto fail_CloneVol;
-	}
-
-	entry->volumeId[ROVOL] = *rovidp;
-    }
-
-    /* If we are creating the ro clone, what are we calling it.
-     * Depends on whether its a temporary clone or not.
-     */
-    if (nottemp) {
-	strcpy(vname, entry->name);
-	strcat(vname, ".readonly");
-    } else {
-	strcpy(vname, "readonly-clone-temp");	/* Should be unique? */
-    }
-
-    /* Create the new clone. If it exists, then reclone it */
-    tst = AFSVolClone(conn, tid, 0, readonlyVolume, vname, rovidp);
-    if (tst == VVOLEXISTS) {
-	tst = AFSVolReClone(conn, tid, *rovidp);
-	if (tst) {
-	    goto fail_CloneVol;
-	}
-    }
-    if (tst) {
-	goto fail_CloneVol;
-    }
-
-    /* Bring the volume back on-line as soon as possible */
-    if (nottemp) {
-	afs_int32 fromtid = 0;
-
-	/* Now bring the RO clone on-line */
-	tst = AFSVolTransCreate(conn, *rovidp, part, ITOffline, &fromtid);
-	if (tst) {
-	    goto fail_CloneVol;
-	}
-
-	tst = AFSVolSetFlags(conn, fromtid, 0);
-	if (tst) {
-	    goto fail_CloneVol;
-	}
-
-	tst = AFSVolEndTrans(conn, fromtid, &rcode);
-	fromtid = 0;
-	if (!tst)
-	    tst = rcode;
-	if (tst) {
-	    goto fail_CloneVol;
-	}
-    }
-
-    /* Get the time the RW was created for return information */
-    tst = AFSVolGetStatus(conn, tid, &volstatus);
-    if (tst) {
-	goto fail_CloneVol;
-    }
-    *vidCreateDate = volstatus.creationDate;
-    rc = 1;
-
-  fail_CloneVol:
-
-    if (tid) {
-	tst = AFSVolEndTrans(conn, tid, &rcode);
-	tid = 0;
-	if (!tst)
-	    tst = rcode;
-	if (tst) {
-	    rc = 0;
-	    goto fail_CloneVol;
-	}
-    }
-
-    if (st != NULL) {
-	*st = tst;
-    }
-    return rc;
-}
-#endif
-
 /* Get a "transaction" on this replica.  Create the volume 
  * if necessary.  Return the time from which a dump should
  * be made (0 if it's a new volume)
